import Link from 'next/link'
import Head from 'next/head'

export default function Privacy() {
    return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
        <Head>
            <title>Live Retail Streaming</title>
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex w-full flex-1 flex-col items-center justify-centre px-20 text-center">
            <h1 className="mt-16 bg-white text-6xl font-b">
                Privacy Policy
            </h1>
            </main>
            <div className="mt-16 prose prose-slate mx-auto lg:prose-lg relative w-full px-6 py-12 bg-white shadow-xl shadow-slate-700/10 ring-1 ring-gray-900/5 md:max-w-3xl md:mx-auto lg:max-w-4xl lg:pt-16 lg:pb-28">
                <p className="lead">Effective date: April 06, 2022</p>
                <p>RunAsh (us, we, or our) operates the RunAsh website (the Service).</p>
                <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. Our Privacy Policy for RunAsh is created with the help of the <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator.php">Free Privacy Policy Generator</a>.</p>
                <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from RunAsh</p>
                <h2>Definitions</h2>
                <ul>
                    <li>
                        <p><strong>Service</strong></p>
                        <p>Service is the RunAsh website operated by RunAsh</p>
                    </li>
                    <li>
                        <p><strong>Personal Data</strong></p>
                        <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                    </li>
                    <li>
                        <p><strong>Usage Data</strong></p>
                        <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    </li>
                    <li>
                        <p><strong>Cookies</strong></p>
                        <p>Cookies are small files stored on your device (computer or mobile device).</p>
                    </li>
                    <p>
                        <strong>Data Controller</strong>
                        <p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
                    </p>
                    <p>
                        <strong>Data Processors (or Service Providers)</strong>
                        <p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
                    </p>
                    <p>
                        <strong>Data Subject (or User)</strong>
                        <p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
                    </p>
                    <p>
                        <strong>Third-party Social Media Service</strong>
                        <p>Third-party Social Media Service means any website or any social network website through which a User can log in or create an account to use the Service.</p>
                    </p>
                    <p>
                        <strong>Personal Data</strong>
                        <p>Personal Data means any information that relates to an identified or identifiable individual.</p>
                    </p>
                    <p>
                        <strong>Usage Data</strong>
                        <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    </p>
                </ul>
                </div>
            </div>
    )
}
        